<?xml version="1.0" encoding="Cp1252"?>
<ChartWindowSetting>
	<version>2</version>
	<tileStyle>0</tileStyle>
	<showToolbar>true</showToolbar>
	<tabbed>false</tabbed>
	<selectedSubchart>0</selectedSubchart>
	<nextSubchartGroupId>1</nextSubchartGroupId>
	<hotButtonStatus>TOOLBAR</hotButtonStatus>
	<ListOfTwsChartSetting varName="listOfSubCharts">
		<TwsChartSettings>
			<title>None</title>
			<timePeriod>-1</timePeriod>
			<timePeriodCount>0</timePeriodCount>
			<timePeriodName></timePeriodName>
			<dynamicOrStatic>true</dynamicOrStatic>
			<updateLine>true</updateLine>
			<forceUserTimeZone>false</forceUserTimeZone>
			<alwaysOnTop>false</alwaysOnTop>
			<useRTH>true</useRTH>
			<timeSales>false</timeSales>
			<showCrosshair>false</showCrosshair>
			<showHotButtons>false</showHotButtons>
			<showButtonsPanel>false</showButtonsPanel>
			<showQuotePanel>false</showQuotePanel>
			<logPriceAxis>false</logPriceAxis>
			<autoTimePeriod>true</autoTimePeriod>
			<fitStudies>true</fitStudies>
			<showVerticalScrollbar>false</showVerticalScrollbar>
			<adjustForDividends>false</adjustForDividends>
			<useTopDataVolUpdates>false</useTopDataVolUpdates>
			<isPrinting>false</isPrinting>
			<enableTradingViewLive>false</enableTradingViewLive>
			<savedDomainStackSize>0</savedDomainStackSize>
			<rangeLowerBound>0.0</rangeLowerBound>
			<rangeUpperBound>0.0</rangeUpperBound>
			<subChartLocationX>2147483647</subChartLocationX>
			<subChartLocationY>2147483647</subChartLocationY>
			<subChartWidth>2147483647</subChartWidth>
			<subChartHeight>2147483647</subChartHeight>
			<subChartDivider>-1</subChartDivider>
			<subchartIcon>false</subchartIcon>
			<showConstantBar>false</showConstantBar>
			<numberOfConstantBar>18</numberOfConstantBar>
			<showChartTrader>false</showChartTrader>
			<chartTraderIsMinimized>false</chartTraderIsMinimized>
			<collapseQuotePanel>false</collapseQuotePanel>
			<showTrades>false</showTrades>
			<showTradesAsShapes>DASHES</showTradesAsShapes>
			<showDailyPnL>false</showDailyPnL>
			<id>0</id>
			<rightMargin>0</rightMargin>
			<showLegend>false</showLegend>
			<autoShowLegend>false</autoShowLegend>
			<showNews>false</showNews>
			<showPriorClose>true</showPriorClose>
			<showQuoteZone>true</showQuoteZone>
			<showBarZone>true</showBarZone>
			<positionIndicatorType>CUSTOM</positionIndicatorType>
			<showPositionIndicator>true</showPositionIndicator>
			<showVwapOnBar>false</showVwapOnBar>
			<highlightLast>true</highlightLast>
			<highlightBidAsk>false</highlightBidAsk>
			<highlightNavLast>false</highlightNavLast>
			<highlightHighLow>false</highlightHighLow>
			<highlightCursorPrice>false</highlightCursorPrice>
			<showDividend>false</showDividend>
			<showCashDividendIndicator>true</showCashDividendIndicator>
			<enableOrderLabel>true</enableOrderLabel>
			<thumbChart>false</thumbChart>
			<tradingViewChart>false</tradingViewChart>
			<daylineup>false</daylineup>
			<showPriceChange>true</showPriceChange>
			<showEstimatedPriceRange>false</showEstimatedPriceRange>
			<markTime>0</markTime>
			<nearTime>0</nearTime>
			<eprStdDevCount>ONE</eprStdDevCount>
			<meetingTime>0</meetingTime>
			<flavor>REGULAR</flavor>
			<allowZeroFeeValue>false</allowZeroFeeValue>
			<subchartGroupId>0</subchartGroupId>
			<hasSubchartGroupStored>false</hasSubchartGroupStored>
			<TwsGraphSettingsMap varName="graphs">
				<GraphKey>
					<name></name>
					<sourceId>0</sourceId>
					<sourceIdUpgraded>0</sourceIdUpgraded>
					<calculationInput>0</calculationInput>
				</GraphKey>
				<TwsGraphSettings>
					<graphName>Template0@Template0</graphName>
					<customName></customName>
					<additional>false</additional>
					<template>true</template>
					<symbol>Template0</symbol>
					<localSymbol>Template0</localSymbol>
					<exchange>Template0</exchange>
					<exchangeGroup></exchangeGroup>
					<aggregateGroup>-1</aggregateGroup>
					<underlying></underlying>
					<tradingClass></tradingClass>
					<listingExchange></listingExchange>
					<description>Template0</description>
					<conid>Template0</conid>
					<secType>Template0</secType>
					<comboKeyString></comboKeyString>
					<scaled>false</scaled>
					<cash>0.0</cash>
					<profit>0.0</profit>
					<factor>1.0</factor>
					<underlyingSpxPrice>0.0</underlyingSpxPrice>
					<comboTypeId>0</comboTypeId>
					<whatToShow>0</whatToShow>
					<whatToShowUpgraded>0</whatToShowUpgraded>
					<outsideRTH>false</outsideRTH>
					<howToShow>7</howToShow>
					<showCandlesticks>true</showCandlesticks>
					<barTypeId>0</barTypeId>
					<showVolumes>true</showVolumes>
					<showPriceHistogram>false</showPriceHistogram>
					<showTotalPutCallValue>true</showTotalPutCallValue>
					<showPutCallRatio>true</showPutCallRatio>
					<showArbitrageMeter>true</showArbitrageMeter>
					<positionIndexInChart>0</positionIndexInChart>
					<setIgnoredInterval>false</setIgnoredInterval>
					<ignoredIntervalStart>0</ignoredIntervalStart>
					<ignoredIntervalEnd>0</ignoredIntervalEnd>
					<lotSize>0</lotSize>
					<CompositeChartContractData varName="compositeData">
						<ListOfChartContractData varName="components"/>
						<offset>0.0</offset>
						<applyMultiplier>false</applyMultiplier>
						<autofit>false</autofit>
						<drawAutofitAsOneLine>true</drawAutofitAsOneLine>
					</CompositeChartContractData>
					<CustomSpreadChartContractData varName="customSpreadData">
						<CustomSpread varName="spread">
							<Tokens varName="tokens"/>
							<id>5</id>
						</CustomSpread>
						<currentMinTickSize>NaN</currentMinTickSize>
					</CustomSpreadChartContractData>
					<scaleFactor>0.0</scaleFactor>
					<yAxisSelection>PRIMARY</yAxisSelection>
					<scaleType>AUTO</scaleType>
					<includePartialBonds>false</includePartialBonds>
					<createdByIndexComparison>false</createdByIndexComparison>
					<useGlobalColors>false</useGlobalColors>
					<expiryType>-1</expiryType>
					<primary>true</primary>
					<fromAPI>false</fromAPI>
					<valueAxisWidth>0</valueAxisWidth>
					<thumbLeftInset>-1</thumbLeftInset>
					<thumbTopInset>-1</thumbTopInset>
					<calculatedValue>false</calculatedValue>
					<L type="jsetting.chart.TwsIndicatorSettings" varName="indicatorSettings">
						<TwsIndicatorVariableMap varName="variableMap"/>
						<TwsIndicatorSettingsList varName="baseSettingsList"/>
					</L>
					<calculationInput>0</calculationInput>
				</TwsGraphSettings>
			</TwsGraphSettingsMap>
			<TwsRemovedDataMap varName="removedDataMap"/>
			<BarReplacementMap varName="replacedDataMap"/>
			<SubPlotHeightMap varName="subPlotHeight">
				<String>Volume</String>
				<Integer>3</Integer>
			</SubPlotHeightMap>
		</TwsChartSettings>
	</ListOfTwsChartSetting>
</ChartWindowSetting>
